import os
import re
import json
import tiktoken
import requests
import pandas as pd
from openai import OpenAI
from .decomposer_agent import DecomposerAgent
from langchain_community.chat_models.gigachat import GigaChat
from langchain_community.chat_models.yandex import ChatYandexGPT
from dotenv import load_dotenv
from src.utils.paths import get_project_path
load_dotenv()

class ChatBot:
    def __init__(self, llm_model):
        """
        Initialize the chatbot instance.

        Args:
            llm_model (str): The name of the language model to use.

        Sets the following instance variables:
            llm_model (str): The name of the language model to use.
            openai_api_key (str): The OpenAI API key.
            openai_api_base (str): The OpenAI API base URL.
            yandex_api_key (str): The Yandex API key.
            yandex_api_base (str): The Yandex API base URL.
            sber_api_key (str): The Sberbank API key.
            decomposer_agent (DecomposerAgent): The decomposer agent instance.
            conversation_history (list): The conversation history.
        """
        self.llm_model = llm_model
        self.openai_api_key = os.environ["OPENAI_API_KEY"]
        self.openai_api_base = os.environ["OPENAI_API_BASE"]
        self.yandex_api_key = os.environ["YANDEX_API_KEY"]
        self.yandex_api_base = os.environ["YANDEX_API_BASE"]
        self.sber_api_key = os.environ['SBER_API_KEY']

        self.decomposer_agent = DecomposerAgent(threshold=0.2)
        self.conversation_history = []

    def get_relevant_documents(self, query, k=10, lambda_mult=0.45, fetch_k=50):

        """
        Queries the vector database using the given query text and parameters.

        Args:
            query (str): The query text to search with.
            k (int, optional): The number of relevant documents to fetch. Defaults to 10.
            lambda_mult (float, optional): The lambda multiplier for the mmr search. Defaults to 0.45.
            fetch_k (int, optional): The number of documents to fetch from the index. Defaults to 50.

        Returns:
            List[dict]: A list of dictionaries containing the relevant documents.
        """
        url = "http://localhost:8000/query"
        payload = {"query": query, "k": k, "lambda_mult": lambda_mult, "fetch_k": fetch_k}
        response = requests.post(url, json=payload)
        print(response)
        if response.status_code == 200:
            return response.json().get('documents', [])
        else:
            raise Exception(f"Error when querying the vector database: {response.text}")

    def generate_response(self, question):
        """
        Generates a response to a given question.

        The response is generated by querying a vector database for relevant documents and
        then using a language model to generate a response based on the context provided by
        the documents. The context is summarized and provided to the language model as a
        system message to help it generate a better response.

        The language model is also provided with a prompt that includes the question and
        information about how to answer it.

        If the response is deemed incomplete or inaccurate, the method calls itself
        recursively to generate a new response.

        Args:
            question (str): The question to answer.

        Returns:
            str: The generated response.
        """
        self.conversation_history.append({"role": "user", "content": question})

        total_tokens = self.count_tokens(self.conversation_history)
        max_model_tokens = 4096
        max_reply_tokens = 1000
        max_allowed_tokens = max_model_tokens - max_reply_tokens - 100

        if total_tokens > max_allowed_tokens:
            N = 4
            messages_to_summarize = self.conversation_history[:-N]
            recent_messages = self.conversation_history[-N:]
            summary = self.summarize_messages(messages_to_summarize)
            summary_message = {"role": "system", "content": f"Summary of the previous conversation: {summary}"}
            self.conversation_history = [summary_message] + recent_messages

        if self.decomposer_agent.should_use_database(question):
            documents = self.get_relevant_documents(question)
            context_parts = []
            for doc in documents:
                content = doc.get("content", {})
                metadata = doc.get("metadata", {})
                filename = metadata.get("filename", "unknown_file")
                context_parts.append(f"{content} [{filename}]")

            context = "\n\n".join(context_parts)

            prompt = (
                # f"You have been provided with the following contextual information:\n\n"
                # f"{context}\n\n"
                # "Based on this information, give a clear, coherent, and professional answer to the following question:\n\n"
                # f"Question: {question}\n\n"
                # "Your answer should be written in a free yet professional style, using all the technical details provided in the context. Avoid structuring the "
                # "text as lists or subheadings, except when necessary to clarify complex technical details. Focus on creating a continuous text that highlights the key technical aspects"
                # "If there is insufficient information in the context, honestly acknowledge this, but try to suggest logical next stepsto resolve the issue"
                # "When using data from the context, be sure to include references in square brackets. References must be formatted according to the information provided: the file name is placed in square brackets. Do not ignore this condition under any circumstances!!!"
                # "Use only those links that are explicitly specified in the context!"
                
                "You have been provided with the following contextual information:\n\n"
                f"Contest: {context}\n\n"
                "Begin with a concise checklist (3-7 bullets) of what you will do; keep items conceptual, not implementation-level.\n\n"
                "Based on this information, provide a clear, coherent, and professional answer to the following question:\n\n"
                f"Question: {question}\n\n"
                "Your response should be composed in a free, professional style, incorporating all technical details from the context. Avoid structuring your text as lists or subheadings unless it is necessary to clarify complex technical details. Focus on crafting a continuous, cohesive narrative that emphasizes the key technical aspects.\n\n"
                "If there is insufficient information in the context, acknowledge this openly, but suggest logical next steps to address the issue.\n\n"
                "When referencing data from the context, include references in square brackets, formatted using the file name provided in the context (e.g., [file_name.pdf])!!! Adhere strictly to this referencing requirement under all circumstances!!! The square brackets should only contain the file name, nothing else!\n\n"
                "After providing your answer, briefly validate whether all key technical details from the context were addressed and state any information gaps or uncertainties.\n\n"
                "Only use links that are explicitly mentioned in the context! Do not introduce links from external sources!"
            )

        else:
            prompt = (
                "Provide a clear, detailed, and professional answer to the following question:\n\n"
                f"Question: {question}"
            )

        messages = self.conversation_history.copy()
        messages.append({"role": "user", "content": prompt})
        
        if self.llm_model == "YandexGPT4":
            llm_yandex_gpt = ChatYandexGPT(
                    api_key=self.yandex_api_key,
                    model_uri=self.yandex_api_base,
                    model_name="yandexgpt-32k",
                    temperature=0.2,
                    max_tokens=4096,
                    messages=messages
                )
            
            reply = llm_yandex_gpt.invoke(prompt).content

        elif self.llm_model == "GigaChat-Pro":
            llm_gigachat = GigaChat(
                    credentials=self.sber_api_key,
                    verify_ssl_certs=False,
                    temperature=0.2,
                    max_tokens=4096,
                    model="GigaChat-Pro"
                )   
            reply = llm_gigachat.invoke(prompt).content
            
        elif self.llm_model == "gpt-oss:latest":
            
            url = os.getenv("LOCAL_API_BASE")
            headers = {"Authorization": f"Bearer {os.getenv("LOCAL_API_KEY")}"}
            data = {
                "model": "gpt-oss:latest",
                "messages": messages,
                "temperature": 0.2,
                "max_tokens": 4096
            }
            
            response = requests.post(url, headers=headers, json=data)
            reply = response.json().get('choices')[0].get('message').get('content')

        else:
            print(f"Model {self.llm_model} is used. ")    

            messages = self.limit_tokens(messages, max_tokens=max_allowed_tokens)

            openai_client = OpenAI(base_url=self.openai_api_base)

            response = openai_client.chat.completions.create(
                model=self.llm_model,
                messages=messages,
                temperature=0.2,
                max_tokens=4096,
            )

            reply = response.choices[0].message.content.strip()

        self.conversation_history.append({"role": "assistant", "content": reply})

        if self.judge_answer(reply, question) == "No" or self.judge_answer(reply, question) == "No.":
            return self.handle_incomplete_answer(question)
        
        df = pd.read_csv(os.path.join(get_project_path(), "data", "updated_references_links.csv"))
        finde_links_in_answer = self.extract_bracket_content(reply)
        new_answer = reply
        for link in finde_links_in_answer:
            for i in df["filename"].values:
                if link in i:
                    new_link = df[df["filename"] == i].iloc[0].link_name
                    new_answer = new_answer.replace(link, new_link)
                
        return new_answer


    def judge_answer(self, answer, question):
        """
        Evaluates the given answer to the given question.

        The evaluation is done by creating a prompt that asks a language model to judge the answer.
        The prompt provides the question and the answer and asks the model to respond with 'Yes' if the answer is complete, accurate, and relevant and 'No' if the answer is incomplete or inaccurate.

        Args:
            answer (str): The answer to be evaluated.
            question (str): The question that the answer is supposed to answer.

        Returns:
            str: The verdict of the language model, either 'Yes' or 'No'.
        """
        prompt = (
            # f"Evaluate whether the following answer complies with the given question. The answer must be complete, accurate, and relevant:\n\n"
            # f"Question: {question}\n\n"
            # f"Answer: {answer}\n\n"
            # "If the answer indicates that the information is insufficient, the question remains open, or the context does not contain an answer, answer 'No' "
            # "If the answer fully meets the criteria of accuracy, completeness, and relevance, answer 'Yes' "
            
            "Assess whether the provided answer satisfies the requirements stated in the question. Ensure the answer is complete, accurate, and relevant to the question.\n\n"
            "Begin with a concise checklist (3-5 bullets) summarizing the criteria you will evaluate: (1) Completeness relative to the question, (2) Factual accuracy, (3) Relevance to the question, (4) Explicit coverage of all requirements, (5) Absence of ambiguity or open issues.\n\n"
            f"Question: {question}\n\n"
            f"Answer: {answer}\n\n"
            "Instructions:\n\n"
            "- If the answer states that the information is insufficient, the question is still open, or the context does not provide an answer, reply with 'No'.\n\n"
            "- If the answer is fully accurate, complete, and relevant, reply with 'Yes'.\n\n"
            "- If the answer is partially correct, only somewhat complete or relevant, reply with 'No'.\n\n"
            "- For any ambiguous or borderline cases where it is unclear whether the criteria are fully met, default to 'No' to maintain strict compliance.\n\n"
            "After making your assessment, validate your choice in 1-2 lines by explicitly stating which checklist items are satisfied or not.\n\n"
            "The output format must be either “Yes” or “No”.\n\n"
            
        )

        # openai_client = OpenAI(base_url=self.openai_api_base)
        # response = openai_client.chat.completions.create(
        #     model="openai/gpt-4o-mini",
        #     messages=[{"role": "user", "content": prompt}],
        #     max_tokens=10,
        #     temperature=0,
        # )
        # verdict = response.choices[0].message.content.strip().lower()
        
            
        url = os.getenv("LOCAL_API_BASE")
        headers = {"Authorization": f"Bearer {os.getenv("LOCAL_API_KEY")}"}
        data = {
            "model": "gpt-oss:latest",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0,
            "max_tokens": 10
        }
        
        response = requests.post(url, headers=headers, json=data)
        verdict = response.json().get('choices')[0].get('message').get('content')

        return verdict

    def handle_incomplete_answer(self, question):
        """
        Handles incomplete answers by reformulating the question.

        When the answer is evaluated as incomplete, this method is called to generate a new question.
        The new question is created by asking a language model to reformulate the original question.
        The reformulated question is then passed to the generate_response method to generate a new answer.

        Args:
            question (str): The original question that received an incomplete answer.

        Returns:
            str: The answer to the reformulated question.
        """
        prompt = (
            f"The answer to the following question was insufficient. Reformulate it while preserving its original meaning::\n\n"
            f"Question: {question}\n\n"
            "Suggest a revised version of the question."
        )

        # openai_client = OpenAI(base_url=self.openai_api_base)
        # response = openai_client.chat.completions.create(
        #     model="openai/gpt-4o-mini",
        #     messages=[{"role": "user", "content": prompt}],
        #     max_tokens=100,
        #     temperature=0.5,
        # )

        # reformulated_question = response.choices[0].message.content.strip()
        
        url = os.getenv("LOCAL_API_BASE")
        headers = {"Authorization": f"Bearer {os.getenv("LOCAL_API_KEY")}"}
        data = {
            "model": "gpt-oss:latest",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.5,
            "max_tokens": 100
        }
        
        response = requests.post(url, headers=headers, json=data)
        reformulated_question = response.json().get('choices')[0].get('message').get('content')
        
        return self.generate_response(reformulated_question)

    def summarize_messages(self, messages):
        """
        Summarizes a conversation between a user and the chatbot.

        This method takes a list of messages as input, where each message is a dictionary containing the role of the sender (user or assistant) and the content of the message.
        The method returns a string that summarizes the conversation, preserving important details.

        The summary is generated by asking a language model to summarize the conversation.
        The language model is provided with a prompt that includes the conversation and the instruction to summarize it.
        The summary is then extracted from the language model's response.

        Args:
            messages (list): A list of dictionaries, where each dictionary contains the role of the sender (user or assistant) and the content of the message.

        Returns:
            str: A string that summarizes the conversation, preserving important details.
        """
        conversation = ""
        for message in messages:
            role = "User" if message['role'] == 'user' else "Assistant"
            conversation += f"{role}: {message['content']}\n"

        prompt = (
            f"Begin with a concise checklist (3-7 bullets) describing the major elements or events in the conversation. Then, provide a concise summary of the following conversation between the user and the assistant, ensuring that all key details are retained: {conversation}.\n\n"
            "After generating the summary, validate that all significant points and facts have been included and correct the summary if any important detail is missing."
        )

        messages = [{"role": "user", "content": prompt}]

        # openai_client = OpenAI(base_url=self.openai_api_base)
        # response = openai_client.chat.completions.create(
        #     model="openai/gpt-4o-mini",
        #     messages=messages,
        #     max_tokens=4096,
        #     temperature=0.2,
        # )
        # summary = response.choices[0].message.content.strip()
        
        url = os.getenv("LOCAL_API_BASE")
        headers = {"Authorization": f"Bearer {os.getenv("LOCAL_API_KEY")}"}
        data = {
            "model": "gpt-oss:latest",
            "messages": messages,
            "temperature": 0.2,
            "max_tokens": 4096
        }
        
        response = requests.post(url, headers=headers, json=data)
        summary = response.json().get('choices')[0].get('message').get('content')
        
        return summary

    def count_tokens(self, messages):
        """
        Counts the total number of tokens in a list of messages.

        Args:
            messages (List[Dict[str, str]]): A list of dictionaries with 'role' and 'content' keys, each containing a message from the conversation.

        Returns:
            int: The total number of tokens in the conversation.
        """
        encoding = tiktoken.encoding_for_model('gpt-4o-mini')
        total_tokens = 0
        for message in messages:
            total_tokens += len(encoding.encode(message['content']))
        return total_tokens

    def limit_tokens(self, messages, max_tokens):
        """
        Limits the total number of tokens in a list of messages to a given maximum value.

        Args:
            messages (List[Dict[str, str]]): A list of dictionaries with 'role' and 'content' keys, each containing a message from the conversation.
            max_tokens (int): The maximum number of tokens allowed in the conversation.

        Returns:
            List[Dict[str, str]]: A list of dictionaries with 'role' and 'content' keys, each containing a message from the conversation, limited to the given maximum number of tokens.
        """
        encoding = tiktoken.encoding_for_model('gpt-4o-mini')
        total_tokens = 0
        limited_messages = []
        for message in reversed(messages):
            message_tokens = len(encoding.encode(message['content']))
            if total_tokens + message_tokens > max_tokens:
                break
            limited_messages.insert(0, message)
            total_tokens += message_tokens
        return limited_messages

    def extract_bracket_content(self, text: str):
        return re.findall(r'\[(.*?)\]', text)