[project]
name = "scinanoai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bert-score>=0.3.13",
    "boto3>=1.40.59",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.12.0",
    "gradio>=5.49.1",
    "ipykernel>=7.0.1",
    "langchain>=1.0.2",
    "langchain-community>=0.4",
    "langchain-huggingface>=1.0.0",
    "langchain-openai>=1.0.1",
    "matplotlib>=3.10.7",
    "ollama>=0.6.0",
    "openai>=2.6.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pydantic>=2.11.10",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
    "torchvision>=0.24.0",
    "unstructured>=0.18.15",
    "unstructured-ingest>=1.2.20",
    "uvicorn>=0.38.0",
]
